language: r
sudo: false
script: make
cache: packages

os:
  - linux
#  - osx

addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:cran/imagemagick'
   packages:
     - libmagick++-dev

before_deploy:
  - Rscript -e "rmarkdown::render('manuscript/manuscript.md', output_format = c('redoc::redoc', 'bookdown::pdf_document2', 'rmarkdown::html_document'), output_dir = 'docs')"
  - mv docs/manuscript.html docs/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: docs
  on:
    branch: master
