on:
  push:
    branches:
      - master

name: Build and deploy

jobs:
  Build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: Ender-events/pandoc@master
      - uses: r-lib/actions/setup-r@v1
        with:
            r-version: '3.6.0'
            
      - name: Install pandoc filters
        run: pip install pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos --user

      - name: test pandoc1
        run: |
          echo "Lorem ipsum" > lorem_1.md
          pandoc lorem_1.md -o lorem_1.pdf
          rm lorem_1.md lorem_1.pdf
        
      - name: test pandoc2
        run: make testPandoc

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libpoppler-cpp-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libglu1-mesa-dev
          sudo apt-get install libmagick++-dev

      - name: Install dependencies
        run: make install

      - name: build project
        run: make
        
      - name: generate html
        run: make md2html

      - name: generate docx
        run: make md2word

      - name: prepare deployment
        run: |
          mkdir docs
          mv manuscript.html docs/manuscript.html
          mv manuscript docs/
          mv manuscript.pdf docs/
          mv manuscript.docx docs/
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
