name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  Build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3'
      - uses: r-lib/actions/setup-r@v1
        with:
            r-version: '3.6.0'

      - name: Install pandoc filters
        run: |
          pip install wheel pandoc-fignos pandoc-eqnos pandoc-tablenos pandoc-secnos pandoc-xnos --user
          which pandoc
          which pandoc-fignos
          which pandoc-eqnos
          which pandoc-tablenos
          which pandoc-secnos
          which pandoc-xnos

      - name: Install LaTeX
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
      
      - name: test pandoc0
        run: |
          echo "Lorem ipsum" > lorem_1.md
          pandoc lorem_1.md -o lorem_1.tex

      - name: test pandoc1
        run: |
          wget -O - https://raw.githubusercontent.com/tomduck/pandoc-tablenos/master/demos/demo3.md | pandoc --filter pandoc-xnos -t markdown
        
      - name: test pandoc2
        run: make testPandoc
        
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libpoppler-cpp-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libglu1-mesa-dev
          sudo apt-get install libmagick++-dev

      - name: Install dependencies
        run: make install

      - name: build project
        run: make

      - name: generate html
        run: make md2html

      - name: generate docx
        run: make md2word

      - name: prepare deployment
        run: |
          mkdir docs
          mv manuscript.html docs/manuscript.html
          mv manuscript docs/
          mv manuscript.pdf docs/
          mv manuscript.docx docs/
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
